export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_CURRENCIES = 'REGISTER_CURRENCIES';
export const REGISTER_EXPENSE = 'REGISTER_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const START_EDIT_EXPENSE = 'START_EDIT_EXPENSE';
